# Generated by Django 5.0.6 on 2026-06-06 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('model', models.CharField(choices=[('claude-opus-4-8', 'Claude Opus 4.8'), ('claude-sonnet-4-6', 'Claude Sonnet 4.6'), ('claude-haiku-4-5-20251001', 'Claude Haiku 4.5')], default='claude-sonnet-4-6', max_length=50)),
                ('system_prompt', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('function_path', models.CharField(max_length=200)),
                ('parameters_schema', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.tool')),
            ],
            options={
                'unique_together': {('agent', 'tool')},
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='tools',
            field=models.ManyToManyField(blank=True, through='agents.AgentTool', to='agents.tool'),
        ),
    ]
